import { AlertFeed } from "@/components/alert-feed";
import { TokenTable } from "@/components/token-table";
import { getAlerts, getTokens } from "@/lib/api";
import { currentUser } from "@clerk/nextjs/server";

export default async function AppDashboard() {
  const user = await currentUser();
  const [tokens, alerts] = await Promise.all([getTokens(), getAlerts()]);

  return (
    <div className="px-4 py-10 text-zinc-900">
      <main className="mx-auto flex w-full max-w-5xl flex-col gap-8">
        <header className="space-y-2">
          <p className="text-sm uppercase tracking-wide text-rose-500">
            Dashboard
          </p>
          <h1 className="text-3xl font-semibold">
            Real-time accumulation overview
          </h1>
          <p className="max-w-3xl text-sm text-zinc-500">
            Welcome back, {user?.firstName || user?.emailAddresses[0]?.emailAddress}!
            Real-time accumulation signals from on-chain data.
          </p>
        </header>

        <section className="grid gap-6 md:grid-cols-2">
          <div className="space-y-4 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm">
            <div>
              <h2 className="text-xl font-semibold">Latest alerts</h2>
              <p className="text-sm text-zinc-500">
                High-confidence signals generated by the accumulation engine.
              </p>
            </div>
            <AlertFeed alerts={alerts} tokens={tokens} />
          </div>

          <div className="space-y-4 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm">
            <div>
              <h2 className="text-xl font-semibold">Tracked tokens</h2>
              <p className="text-sm text-zinc-500">
                Latest snapshot of tokens that passed liquidity & risk filters.
              </p>
            </div>
            <TokenTable tokens={tokens} />
          </div>
        </section>
      </main>
    </div>
  );
}

