import { AlertFeed } from "@/components/alert-feed";
import { TokenTable } from "@/components/token-table";
import { getAlerts, getTokens } from "@/lib/api";

export default async function Home() {
  const [tokens, alerts] = await Promise.all([getTokens(), getAlerts()]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-zinc-50 to-white px-4 py-10 text-zinc-900">
      <main className="mx-auto flex w-full max-w-5xl flex-col gap-8">
        <header className="space-y-2">
          <p className="text-sm uppercase tracking-wide text-rose-500">
            ChainWhales.io
          </p>
          <h1 className="text-3xl font-semibold">
            Real-time accumulation overview
          </h1>
          <p className="max-w-3xl text-sm text-zinc-500">
            This dashboard reads from the NestJS backend (`/tokens` and
            `/alerts`). Run the Python engine with the `InternalApiSink` to keep
            the feed updated.
          </p>
        </header>

        <section className="grid gap-6 md:grid-cols-2">
          <div className="space-y-4 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm">
            <div>
              <h2 className="text-xl font-semibold">Latest alerts</h2>
              <p className="text-sm text-zinc-500">
                High-confidence signals generated by the accumulation engine.
              </p>
            </div>
            <AlertFeed alerts={alerts} tokens={tokens} />
          </div>

          <div className="space-y-4 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm">
            <div>
              <h2 className="text-xl font-semibold">Tracked tokens</h2>
              <p className="text-sm text-zinc-500">
                Latest snapshot of tokens that passed liquidity & risk filters.
              </p>
            </div>
            <TokenTable tokens={tokens} />
          </div>
        </section>
      </main>
    </div>
  );
}
