"use client";

import { AlertFeed } from "@/components/alert-feed";
import { TokenTable } from "@/components/token-table";
import { useAlertsSocket } from "@/lib/use-alerts-socket";
import { Alert, Token } from "@/lib/types";

interface DashboardContentProps {
  initialAlerts: Alert[];
  initialTokens: Token[];
}

export function DashboardContent({
  initialAlerts,
  initialTokens,
}: DashboardContentProps) {
  const { alerts, tokens, isConnected } = useAlertsSocket(
    initialAlerts,
    initialTokens
  );

  return (
    <section className="grid gap-6 md:grid-cols-2">
      <div className="space-y-4 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-semibold">Latest alerts</h2>
            <p className="text-sm text-zinc-500">
              High-confidence signals generated by the accumulation engine.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <div
              className={`h-2 w-2 rounded-full ${
                isConnected ? "bg-green-500" : "bg-red-500"
              }`}
              title={isConnected ? "Connected" : "Disconnected"}
            />
            <span className="text-xs text-zinc-500">
              {isConnected ? "Live" : "Offline"}
            </span>
          </div>
        </div>
        <AlertFeed alerts={alerts} tokens={tokens} />
      </div>

      <div className="space-y-4 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm">
        <div>
          <h2 className="text-xl font-semibold">Tracked tokens</h2>
          <p className="text-sm text-zinc-500">
            Latest snapshot of tokens that passed liquidity & risk filters.
          </p>
        </div>
        <TokenTable tokens={tokens} />
      </div>
    </section>
  );
}

